# Generated by Django 3.2.9 on 2022-05-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INaturalistSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('-1', 'Inactivo'), ('1', 'Activo')], default='1', max_length=10)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('auth_code', models.TextField()),
                ('token', models.TextField()),
                ('created', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
